source 'https://rubygems.org'

gem 'sinatra', '~> 2.2.0'
gem 'sinatra-contrib'
gem 'foreman'
gem 'pry'
gem 'taglib-ruby'
gem 'terrapin', '~> 0.6.0'
gem 'dotenv'
gem 'activesupport', '< 5.0'
gem 'puma'
gem 'sidekiq'